AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2.
    Kittens Carousel Static Website will be deployed on Amazon Linux 2023 (latestamiid) EC2 Instance with
    custom security group which allows http connections on port 80 and ssh port 22 from
    anywhere. Kittens Carousel Static Website is downloaded from my Public Github repository,
    then deployed on Apache Web Server.
  
Parameters:
  Keypair:
    Description: Select your keypair 
    Type: AWS::EC2::KeyPair::KeyName
    Default: first-key
  
  InstanceType:
    Description: Select your instance type 
    Type: String
    Default: t2.micro
    AllowedValues:
         - t2.micro
         - t3.micro
    
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
  MySecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for HTTP on port 80 and SSH on port 22
      SecurityGroupIngress:
          - FromPort: 22
            IpProtocol: tcp
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp 
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0 

  WebServerKittens:
    Type: AWS::EC2::Instance
    Properties:
         ImageId: !Ref LatestAmiId
         InstanceType: !Ref InstanceType
         KeyName: !Ref Keypair
         SecurityGroupIds:
              - !Ref MySecGroup
         Tags:
              - Key: Name
                Value: !Sub "Web Server of ${AWS::StackName}"
         UserData: 
            Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd wget

              FOLDER="https://raw.githubusercontent.com/ozayilmz/aws-projects/main/101-kittens-carousel-static-website-ec2/static-web"
              cd /var/www/html
              wget $FOLDER/index.html
              wget $FOLDER/cat0.jpg
              wget $FOLDER/cat1.jpg
              wget $FOLDER/cat2.jpg
              wget $FOLDER/cat3.png

              systemctl start httpd
              systemctl enable httpd

              echo "UserData script completed successfully." > /var/log/userdata.log

Outputs:
  WebSiteURL:
    Description: "Kittens Carousel Static Website URL"
    Value: !Sub "http://${WebServerKittens.PublicDnsName}"
